# Site settings
title: The Duck's Diarrhea
description: 'my personal blog'
description_2: 'cause it would be too mainstream to name it "The Duke Diary"'
url: 'https://duken72.github.io/'
baseurl: ''
google_analytics: 'UA-180068391-1'

author:
  name: 'Duke Nguyen'
  email: duke7295@gmail.com
  facebook_username: dukehn
  github_username: duken72
  linkedin_username: huu-duc-nguyen-689798197
  youtube_username: Duke7295

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

comments:
	provider : "facebook"
	facebook:
		appid : 343864666827805
		num_posts : 7 # 5 (default)
		colorscheme : " light" # "light" (default), "dark"

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
